name: Docker Image CI

on:
  repository_dispatch:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ls
    - name: Install dependencies
      run: |
        docker build . --file Dockerfile

        chmod +x docker-nv-tookkit.sh && ./docker-nv-tookkit.sh
        chmod +x build.sh && ./build.sh

