name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile
    - name: Install dependencies
      run: |
        chmod +x docker-nv-tookkit.sh && ./docker-nv-tookkit.sh
        chmod +x build.sh && ./build.sh
        chmod +x minecraft-launcher.sh && ./minecraft-launcher.sh
